name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push to DH
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: krisjanisp/proglv-docs:latest

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Create kubernetes directory
      run: mkdir -p kubernetes

    - name: Download manifest
      run: wget https://raw.githubusercontent.com/programme-lv/devops/main/kubernetes/docs.programme.lv/docs_deployment.yaml -P kubernetes/

    - name: Replace manifest tokens
      run: |
        sed -e 's/latest/latest/g' \
            < ./kubernetes/docs_deployment.yaml > ./kubernetes/gucci_deployment.yaml

    - name: Log manifest
      run: cat ./kubernetes/gucci_deployment.yaml

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}

    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -f ./kubernetes/gucci_deployment.yaml

    - name: Verify deployment
      run: timeout 30s kubectl rollout status deployment/docs -n proglv

    - name: Display running pods
      run: kubectl get pods -n backend
